name: Deployment

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout is not needed: https://github.com/marketplace/actions/build-and-push-docker-images#usage
      - # https://github.com/marketplace/actions/docker-setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - # https://github.com/marketplace/actions/docker-setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - # https://github.com/marketplace/actions/docker-login
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - # https://github.com/marketplace/actions/build-and-push-docker-images
        name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aceheliflyer/papermc:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=aceheliflyer/papermc:latest
          cache-to: type=inline
