name: Deployment

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Docker Hub
    runs-on: ubuntu-latest
    steps:
      # Checkout is not needed: https://github.com/marketplace/actions/build-and-push-docker-images#usage
      - # https://github.com/marketplace/actions/docker-setup-qemu
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - # https://github.com/marketplace/actions/docker-setup-buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - # https://github.com/marketplace/actions/docker-login
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/marketplace/actions/build-and-push-docker-images
      - # Image for Latest and openjdk16.
        name: Build and Push Java 16
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            aceheliflyer/papermc:latest
            aceheliflyer/papermc:openjdk16
          platforms: linux/amd64,linux/arm64
          build-args: JAVA_VERSION=openjdk16-jre-headless
          cache-from: type=registry,ref=aceheliflyer/papermc:openjdk16
          cache-to: type=inline

      - # Image for openjdk11.
        name: Build and Push Java 11
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aceheliflyer/papermc:openjdk11
          platforms: linux/amd64,linux/arm64
          build-args: JAVA_VERSION=openjdk11-jre-headless
          cache-from: type=registry,ref=aceheliflyer/papermc:openjdk11
          cache-to: type=inline

      - # Image for openjdk8.
        name: Build and Push Java 8
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: aceheliflyer/papermc:openjdk8
          platforms: linux/amd64,linux/arm64
          build-args: JAVA_VERSION=openjdk8-jre-base
          cache-from: type=registry,ref=aceheliflyer/papermc:openjdk8
          cache-to: type=inline
